bases:
  - ./environments.yaml

---
repositories:
  - name: ollama-helm
    url: https://otwld.github.io/ollama-helm/
  - name: open-webui
    url: https://helm.openwebui.com/

templates:
  default:
    namespace: ollama
    values:
      - environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

releases:
# https://artifacthub.io/packages/helm/ollama-helm/ollama
- name: ollama
  chart: ollama-helm/ollama
  version: 0.23.0
  inherit:
    - template: default

# https://github.com/open-webui/helm-charts
- name: open-webui
  chart: open-webui/open-webui
  needs:
    - ollama
  inherit:
    - template: default
